name: Pipeline - Full

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  schedule:
    # nightly
    - cron: 31 10 * * *

permissions:
  security-events: write
  contents: read
  actions: read



jobs:

  dep-tree:
    if: github.actor != 'dependabot[bot]'
    name: maven/dep-tree
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # dependency:tree does NOT compile — much faster than mvn package
      # https://github.com/semgrep/semgrep-docs/issues/2510
      - name: Generate dependency tree
        run: mvn --batch-mode dependency:tree -DoutputFile=maven_dep_tree.txt -f victim/pom.xml

      - name: Upload dependency tree artifact
        uses: actions/upload-artifact@v4
        with:
          name: mavendeptree
          path: victim/maven_dep_tree.txt
          retention-days: 1

  semgrep:
    needs: dep-tree
    if: github.actor != 'dependabot[bot]'
    name: semgrep/full
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Download Maven dependency tree for SCA
        uses: actions/download-artifact@v4
        with:
          name: mavendeptree

      # Full scan: SAST + SCA (uses dep tree) + Secrets
      - name: Semgrep full scan
        run: semgrep ci --sarif > semgrep.sarif

      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
        if: always()

